#ifndef _STM32_STM32F446_INTERRUPTS_H_
#define _STM32_STM32F446_INTERRUPTS_H_

enum {
	INTERRUPT_WWDG = 0,
	INTERRUPT_PVD,
	INTERRUPT_TAMP_STAMP,
	INTERRUPT_RTC_WKUP,
	INTERRUPT_FLASH,
	INTERRUPT_RCC,
	
	INTERRUPT_EXTI0,
	INTERRUPT_EXTI1,
	INTERRUPT_EXTI2,
	INTERRUPT_EXTI3,
	INTERRUPT_EXTI4,
	
	INTERRUPT_DMA1_STREAM0,
	INTERRUPT_DMA1_STREAM1,
	INTERRUPT_DMA1_STREAM2,
	INTERRUPT_DMA1_STREAM3,
	INTERRUPT_DMA1_STREAM4,
	INTERRUPT_DMA1_STREAM5,
	INTERRUPT_DMA1_STREAM6,
	
	INTERRUPT_ADC,
	
	INTERRUPT_CAN1_TX,
	INTERRUPT_CAN1_RX0,
	INTERRUPT_CAN1_RX1,
	INTERRUPT_CAN1_SCE,
	
	INTERRUPT_EXTI9_5,
	
	INTERRUPT_TIM1_BRK_TIM9,
	INTERRUPT_TIM1_UP_TIM10,
	INTERRUPT_TIM1_TRG_COM_TIM11,
	INTERRUPT_TIM1_CC,
	INTERRUPT_TIM2,
	INTERRUPT_TIM3,
	INTERRUPT_TIM4,
	
	INTERRUPT_I2C1_EV,
	INTERRUPT_I2C1_ER,
	INTERRUPT_I2C2_EV,
	INTERRUPT_I2C2_ER,
	
	INTERRUPT_SPI1,
	INTERRUPT_SPI2,
	
	INTERRUPT_USART1,
	INTERRUPT_USART2,
	INTERRUPT_USART3,
	
	INTERRUPT_EXTI15_10,
	
	INTERRUPT_RTC_ALARM,
	INTERRUPT_OTG_FS_WKUP,
	
	INTERRUPT_TIM8_BRK_TIM12,
	INTERRUPT_TIM8_UP_TIM13,
	INTERRUPT_TIM8_TRG_COM_TIM14,
	INTERRUPT_TIM8_CC,
	
	INTERRUPT_DMA1_STREAM7,
	INTERRUPT_FMC,
	INTERRUPT_SDIO,
	INTERRUPT_TIM5,
	INTERRUPT_SPI3,
	INTERRUPT_UART4,
	INTERRUPT_UART5,
	INTERRUPT_TIM6_DAC,
	INTERRUPT_TIM7,
	
	INTERRUPT_DMA2_STREAM0,
	INTERRUPT_DMA2_STREAM1,
	INTERRUPT_DMA2_STREAM2,
	INTERRUPT_DMA2_STREAM3,
	INTERRUPT_DMA2_STREAM4,
	
	INTERRUPT_CAN2_TX = 63,
	INTERRUPT_CAN2_RX0,
	INTERRUPT_CAN2_RX1,
	INTERRUPT_CAN2_SCE,
	
	INTERRUPT_OTG_FS,
	
	INTERRUPT_DMA2_STREAM5,
	INTERRUPT_DMA2_STREAM6,
	INTERRUPT_DMA2_STREAM7,
	
	INTERRUPT_USART6,
	
	INTERRUPT_I2C3_EV,
	INTERRUPT_I2C3_ER,
	
	INTERRUPT_OTG_HS_EP1_OUT,
	INTERRUPT_OTG_HS_EP1_IN,
	INTERRUPT_OTG_HS,
	
	INTERRUPT_DMCI,
	
	INTERRUPT_FPU = 81,
	
	INTERRUPT_SPI4 = 84,
	
	INTERRUPT_SAI1 = 87,
	INTERRUPT_SAI2 = 98,
	
	INTERRUPT_QSPI,
	INTERRUPT_HDMI_CEC,
	INTERRUPT_SPDIF_RX,
	
	INTERRUPT_FMPI2C1,
	INTERRUPT_FMPI2C1_ERROR,
	
	INTERRUPTS,
};

#endif
