#ifndef _STM32_STM32F0XX_INTERRUPTS_H_
#define _STM32_STM32F0XX_INTERRUPTS_H_

enum {
	INTERRUPT_WWDG,
	INTERRUPT_PVD_VVDIO2,
	INTERRUPT_RTC,
	INTERRUPT_FLASH,
	INTERRUPT_RCC_CRS,
	INTERRUPT_EXTI0_1,
	INTERRUPT_EXTI2_3,
	INTERRUPT_EXTI4_15,
	INTERRUPT_TSC,
	INTERRUPT_DMA_CH1,
	INTERRUPT_DMA_CH23,
	INTERRUPT_DMA_CH4_5_6_7,
	INTERRUPT_ADC_COMP,
	INTERRUPT_TIM1_BRK_UP_TRG_COM,
	INTERRUPT_TIM1_CC,
	INTERRUPT_TIM2,
	INTERRUPT_TIM3,
	INTERRUPT_TIM6_DAC,
	INTERRUPT_TIM7,
	INTERRUPT_TIM14,
	INTERRUPT_TIM15,
	INTERRUPT_TIM16,
	INTERRUPT_TIM17,
	INTERRUPT_I2C1,
	INTERRUPT_I2C2,
	INTERRUPT_SPI1,
	INTERRUPT_SPI2,
	INTERRUPT_USART1,
	INTERRUPT_USART2,
	INTERRUPT_USART3_4_5_6_7_8,
	INTERRUPT_CEC_CAN,
	INTERRUPT_USB,
	
	INTERRUPTS
};

#endif
