#ifndef _STM32_EXCEPTIONS_H_
#define _STM32_EXCEPTIONS_H_

typedef enum STM32Exception STM32Exception;
enum STM32Exception {
	EXCEPTION_NMI = 2,
	EXCEPTION_HARD_FAULT,
	EXCEPTION_MEM_MANAGE,
	EXCEPTION_BUS_FAULT,
	EXCEPTION_USAGE_FAULT,
	
	EXCEPTION_SV_CALL = 11,
	EXCEPTION_DEBUG_MONITOR,
	
	EXCEPTION_PEND_SV = 14,
	EXCEPTION_SYSTICK,
};

#endif
